import keyMirror from 'keymirror'

export default keyMirror({
  CLOSE_CONFIRM_MODAL: null,
  CLOSE_MODAL: null,
  CLOSE_RIGHT_DRAWER: null,
  INIT_CHAIN_ID: null,
  INIT_PROVIDER: null,
  OPEN_MODAL: null,
  OPEN_CONFIRM_MODAL: null,
  OPEN_RIGHT_DRAWER: null,
  SET_PROVIDER: null,
  MINT_TOKENS: null,
  MINT_TOKENS_MSG: null,
  MINT_TOKENS_TX: null,
  CHANGE_CONTRACT_OWNER: null,
  CHANGE_CONTRACT_OWNER_MSG: null,
  CHANGE_CONTRACT_OWNER_TX: null,
  CONNECT_METAMASK: null,
  SET_CHAIN_ID: null,
  SET_METAMASK_CONNECTION: null,
  DISPLAY_METAMASK_INSTALL_PROMPT: null,
  METAMASK_ACCOUNT_CHANGE: null,
  CLOSE_SNACK_BAR: null,
  UPDATE_TOKEN_INFO: null,
  UPDATE_OWNER_INFO: null
})
